#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other compatible shell available, you may
#       want to edit this line so it runs that shell.
#   (2) Avoid modifying this script unless you know what you are doing -- it's
#       best to leave the defaults, and modify values in the build.gradle files
#       instead.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a symlink
PRG="$0"
# Need this for daisy-chained symlinks.
while [ -h "$PRG" ] ; do
    ls=$(ls -ld "$PRG")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=$(dirname "$PRG")"/$link"
    fi
done
SAVEDIR=$(pwd)
cd "$(dirname \"$PRG\")"/.. >/dev/null
APP_HOME=$(pwd -P)
cd \"$SAVEDIR\" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=$(basename \"$0\")

# Add default JVM options
DEFAULT_JVM_OPTS='\" -Xmx64m -Xms64m \"'

# Use the maximum available, or set MAX_FD != unlimited.
MAX_FD=\"maximum\"

warn ( ) {
    echo \"$*\"
} >&2

die ( ) {
    echo \"\"
    echo \"ERROR: $*\"
    echo \"\"
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
IS_CYGWIN=false
IS_MSYS=false
IS_MINGW=false
case \"$(uname)\" in
  CYGWIN* )
    IS_CYGWIN=true
    ;;
  Darwin* )
    IS_MACOSX=true
    ;;
  MSYS* )
    IS_MSYS=true
    ;;
  MINGW* )
    IS_MINGW=true
    ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n \"$JAVA_HOME\" ] ; then
    if [ -x \"$JAVA_HOME/jre/sh/java\" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=\"$JAVA_HOME/jre/sh/java\"
    else
        JAVACMD=\"$JAVA_HOME/bin/java\"
    fi
    if [ ! -x \"$JAVACMD\" ] ; then
        die \"ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.\"
    fi
else
    JAVACMD=\"java\"
    which java >/dev/null 2>&1 || die \"ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.\"
fi

if [ -z \"$JAVA_HOME\" ] ; then
    warn \"JAVA_HOME environment variable is not set\"
fi

LOCATION=\"$0\"
if [ \"$IS_CYGWIN\" = \"true\" ] ; then
    LOCATION=$(cygpath --windows \"$LOCATION\")
fi

SETCLASSPATH=\"$APP_HOME/gradle/wrapper/gradle-wrapper.jar\"
if [ -n \"$CLASSPATH\" ] ; then
    CLASSPATH=\"$SETCLASSPATH:$CLASSPATH\"
else
    CLASSPATH=\"$SETCLASSPATH\"
fi

if [ \"$IS_CYGWIN\" = \"true\" ] ; then
    APP_HOME=$(cygpath --path --mixed \"$APP_HOME\")
    CLASSPATH=$(cygpath --path --mixed \"$CLASSPATH\")
    JAVACMD=$(cygpath --unix \"$JAVACMD\")
fi

if [ \"$IS_MINGW\" = \"true\" ] ; then
    APP_HOME=$(( cd \"$(dirname \"$PRG\")\"; pwd )
)
    CLASSPATH=\"$APP_HOME/gradle/wrapper/gradle-wrapper.jar\"
fi

if [ \"$IS_MSYS\" = \"true\" ] ; then
    APP_HOME=$(( cd \"$(dirname \"$PRG\")\"; pwd )
)
    CLASSPATH=\"$APP_HOME/gradle/wrapper/gradle-wrapper.jar\"
fi

exec \"$JAVACMD\" $DEFAULT_JVM_OPTS -classpath \"$CLASSPATH\" org.gradle.wrapper.GradleWrapperMain \"$@\"
